tupla = (0, 1, 2, 'Hola', True)
#tupla[1] = 'Aprendiendo Python' # error
print(tupla[0])
print(tupla[3])
print(tupla[-1])
print(tupla[1:3])
print(tupla[0:3])
print(tupla[:3])
print(len(tupla))
print(tupla.count('Hola'))
print(tupla.index('Hola'))