print('Esto es un' + ' ' + 'texto')
print('Mi nombre es {} {}'.format('Pablo', 'España'))
print('Mi nombre es {0} {1}'.format('Pablo', 'España'))
print('Su nombre es {0} {1}, bienvenidos al curso de {2}'.format('Pablo', 'España', 'Python'))
print('Su nombre es {1} {0}, bienvenidos al curso de {2}'.format('Pablo', 'España', 'Python'))
print('Su nombre es {1} {0}, bienvenidos al curso de {2}'.format(input('Ingrese su nombre: '), input('Ingrese su apellido: '), 'Python'))