print('Bienvenidos')
print("Bienvenidos")
print('Bienvenidos', end='\n')
print('al curso')
print('Bienvenidos', 'al curso', 'de Python', sep='.')
print('Bienvenidos', 'al curso', 'de Python', sep='\n')
print('Bienvenidos', 'al curso', 'de Python', sep='\n', end='\n---Termina el mensaje--')
print(1, end='.')
print(1, 2, 3, 4, 5, 6,  end='\n')